- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      #shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
      #apt_repository:
        #repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        #repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Update apt Cache 
      ansible.builtin.apt: 
        update_cache: yes 
