--- 
- name: Install Grafana 
  hosts: hosts 
  become: yes 
  
  tasks: 
  - name: Download apt key 
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      #id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6 # Replace value 
      state: absent 
  - name: Add grafana repo to source.list 
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana 
      state: absent 
 
  - name: Make sure Grafana is StopS
    ansible.builtin.systemd: 
      state: stopped 
      enabled: no
      name: grafana-server
  - name: Remove Grafana 
    ansible.builtin.apt: 
      name: grafana 
      state: absent 
