################ test config 11/20 works. Ensure name is added to the start block. 
- name: Install Jenkins
  hosts: main 
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      #url: https://pkg.jenkins.io/debian/jenkins.io.key
      state: present

  - name: Ensure Jenkins repository file is removed if malformed
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/jenkins.list
      state: absent

  - name: Add Jenkins repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins
  
  - name: Update apt cache and Install Jenkins
    ansible.builtin.apt: 
      name: jenkins 
      update_cache: yes  
  
  - name: Install openjdk-17-jdk
    apt: 
      name: openjdk-17-jdk
      state: present 
      update_cache: yes 

  - name: Start Jenkins and enable 
    ansible.builtin.systemd:
      name: jenkins
      state: started 
      enabled: yes
